// <auto-generated />
namespace FixWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class APiUrls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(APiUrls));
        
        string IMigrationMetadata.Id
        {
            get { return "202305291233332_APiUrls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
