// <auto-generated />
namespace FixWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventidchangestomarketid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventidchangestomarketid));
        
        string IMigrationMetadata.Id
        {
            get { return "202305300629337_eventid changes to marketid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
