// <auto-generated />
namespace FixWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class casinogames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(casinogames));
        
        string IMigrationMetadata.Id
        {
            get { return "202305190712571_casino games"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
